# Generated by Django 6.0.6 on 2026-06-09 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_date_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='razón social')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='código postal')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('clients', models.ManyToManyField(related_name='suppliers', to='core.client', verbose_name='clientes')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
